import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Poppins } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "~/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



const headings = Poppins({
  subsets: ["latin"],
  variable: "--font-headings",
  weight: ["300", "500", "400", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${headings.variable} dark`}>
      <body className="overflow-x-hidden">
        <div className="dark fixed top-0 z-[-2] h-screen w-screen bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.4),rgba(255,255,255,0))]"></div>

        <TRPCReactProvider>
          <div className="flex min-h-screen flex-col">
            <Toaster />
            <main className="mx-auto flex w-full flex-1 flex-col md:max-w-7xl">
              {children}
            </main>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
